version: "3"
services:

  frontend:
    build: .
    ports:
      - "5000:5000"
    environment:
      # - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public

  express:
    build: uad_backend/.
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./geojson:/geojson
      - mongo_data:/data
  
volumes:
  mongo_data: {}