version: "3"
services:

  frontend:
    build: server/.
  depends_on:
    - mongo
  links:
    - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./geojson:/geojson
      - mongo_data:/data
  
volumes:
  mongo_data: {}