version: "3"
services:

  frontend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/usr/src/app
      - ./public:/usr/src/app/public
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./geojson:/geojson
      - mongo_data:/data
  
volumes:
  mongo_data: {}